"""add_clauses_risks_summaries_chat_comparisons_tables

Revision ID: 2f138a140baf
Revises: ced2a6cf280a
Create Date: 2026-07-14 15:06:04.449617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f138a140baf'
down_revision: Union[str, Sequence[str], None] = 'ced2a6cf280a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_role_enum', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_contract_id'), 'chat_messages', ['contract_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('contract_a_id', sa.UUID(), nullable=False),
    sa.Column('contract_b_id', sa.UUID(), nullable=False),
    sa.Column('added_clauses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('removed_clauses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('modified_clauses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_obligations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_a_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_b_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_project_id'), 'comparisons', ['project_id'], unique=False)
    op.create_table('detected_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.Enum('UNLIMITED_LIABILITY', 'AUTOMATIC_RENEWAL', 'MISSING_TERMINATION', 'MISSING_CONFIDENTIALITY', 'MISSING_INTELLECTUAL_PROPERTY', 'VENDOR_FAVORABLE_JURISDICTION', 'VAGUE_PAYMENT_TERMS', 'MISSING_NOTICE_PERIOD', name='risk_type_enum', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity_enum', create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_risks_contract_id'), 'detected_risks', ['contract_id'], unique=False)
    op.create_table('executive_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('important_dates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_terms', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_obligations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('major_risks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_summaries_contract_id'), 'executive_summaries', ['contract_id'], unique=True)
    op.create_table('extracted_clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('clause_type', sa.Enum('PAYMENT_TERMS', 'TERMINATION', 'CONFIDENTIALITY', 'INTELLECTUAL_PROPERTY', 'GOVERNING_LAW', 'LIABILITY', 'INDEMNIFICATION', 'RENEWAL', 'ARBITRATION', 'FORCE_MAJEURE', 'NON_COMPETE', name='clause_type_enum', create_constraint=True), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_clauses_contract_id'), 'extracted_clauses', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_clauses_contract_id'), table_name='extracted_clauses')
    op.drop_table('extracted_clauses')
    op.drop_index(op.f('ix_executive_summaries_contract_id'), table_name='executive_summaries')
    op.drop_table('executive_summaries')
    op.drop_index(op.f('ix_detected_risks_contract_id'), table_name='detected_risks')
    op.drop_table('detected_risks')
    op.drop_index(op.f('ix_comparisons_project_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_chat_messages_contract_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
